# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_LDLT <- function(a, b) {
    .Call('_sanic_solve_LDLT', PACKAGE = 'sanic', a, b)
}

solve_SLDLT <- function(a, b) {
    .Call('_sanic_solve_SLDLT', PACKAGE = 'sanic', a, b)
}

solve_PPLU <- function(a, b) {
    .Call('_sanic_solve_PPLU', PACKAGE = 'sanic', a, b)
}

solve_SLU <- function(a, b) {
    .Call('_sanic_solve_SLU', PACKAGE = 'sanic', a, b)
}

solve_CPHQR <- function(a, b) {
    .Call('_sanic_solve_CPHQR', PACKAGE = 'sanic', a, b)
}

solve_SQR <- function(a, b) {
    .Call('_sanic_solve_SQR', PACKAGE = 'sanic', a, b)
}

solve_BiCGSTAB <- function(a, b, x0, tol = 0, iter = 0L, verbose = FALSE) {
    .Call('_sanic_solve_BiCGSTAB', PACKAGE = 'sanic', a, b, x0, tol, iter, verbose)
}

solve_LSCG <- function(a, b, x0, tol = 0, iter = 0L, verbose = FALSE) {
    .Call('_sanic_solve_LSCG', PACKAGE = 'sanic', a, b, x0, tol, iter, verbose)
}

solve_CG <- function(a, b, x0, tol = 0, iter = 0L, verbose = FALSE) {
    .Call('_sanic_solve_CG', PACKAGE = 'sanic', a, b, x0, tol, iter, verbose)
}

