# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_LL <- function(a, b, pivot = 0L) {
    .Call('_sanic_solve_LL', PACKAGE = 'sanic', a, b, pivot)
}

solve_SLL <- function(a, b, pivot = 0L, ordering = 0L) {
    .Call('_sanic_solve_SLL', PACKAGE = 'sanic', a, b, pivot, ordering)
}

solve_LU <- function(a, b, pivot = 0L) {
    .Call('_sanic_solve_LU', PACKAGE = 'sanic', a, b, pivot)
}

solve_SLU <- function(a, b, ordering = 0L) {
    .Call('_sanic_solve_SLU', PACKAGE = 'sanic', a, b, ordering)
}

solve_HQR <- function(a, b, pivot = 0L) {
    .Call('_sanic_solve_HQR', PACKAGE = 'sanic', a, b, pivot)
}

solve_SQR <- function(a, b, ordering = 0L) {
    .Call('_sanic_solve_SQR', PACKAGE = 'sanic', a, b, ordering)
}

solve_BiCGSTAB <- function(a, b, x0, tol = 0, iter = 0L, precond = 0L, verbose = FALSE) {
    .Call('_sanic_solve_BiCGSTAB', PACKAGE = 'sanic', a, b, x0, tol, iter, precond, verbose)
}

solve_LSCG <- function(a, b, x0, tol = 0, iter = 0L, precond = 0L, verbose = FALSE) {
    .Call('_sanic_solve_LSCG', PACKAGE = 'sanic', a, b, x0, tol, iter, precond, verbose)
}

solve_CG <- function(a, b, x0, tol = 0, iter = 0L, precond = 0L, verbose = FALSE) {
    .Call('_sanic_solve_CG', PACKAGE = 'sanic', a, b, x0, tol, iter, precond, verbose)
}

is_symmetric2 <- function(x, tol = 0) {
    .Call('_sanic_is_symmetric2', PACKAGE = 'sanic', x, tol)
}

is_symmetric <- function(x, tol = 0) {
    .Call('_sanic_is_symmetric', PACKAGE = 'sanic', x, tol)
}

